export { default as Categories } from './Categories/Categories';
export { default as Figure } from './/Figure/Figure';
export { default as Header } from './Header/Header';
export { default as Hint } from './Hint/Hint';
export { default as Keyboard } from './Keyboard/Keyboard';
export { default as Modal } from './Modal/Modal';
export { default as Notification } from './Notification/Notification';
export { default as WrongLetters } from './WongLetters/WrongLetters';
export { default as Word } from './Word/Word';
